Add support to configure server port
beeceej/iGo pull request #18
Opened 2019-09-14 18:51 UTC by sowmiyamuthuraman

Fixes #14

2019-09-16 15:44 UTC, beeceej requested changes
I noticed a couple things, let me know when you sort those out and I can take another look!

Thanks!

EDIT:
also, don't worry about tests for now. I haven't even spend time setting those up myself (though, those are in the works)

2019-09-16 15:44 UTC, beeceej commented on igo/igod/server.go
> +func (s *Server) Run(port string) {
I think it would make more sense if port were a property on the Server struct.

2019-09-16 15:44 UTC, beeceej commented on igo/igod/server.go
> +	fmt.Println(port)
let's remove this for now, we probably will want more robust diagnostic logs in the future, but that can come later.

2019-09-16 15:44 UTC, beeceej commented on .config/igo/config.toml
> +port = "9999"
the location for this file would be in the users home directory, so I don't think we need to commit this file

2019-09-16 15:44 UTC, beeceej commented on cmd/igod/main.go
> +		if _, err := toml.DecodeFile(".config/igo/config.toml", &configuration); err != nil {
I would use `filepath.Join(os.Getenv("HOME"), ".config", "igo", "config.toml")`.

the location for this file would be in the users home directory which is why I would recommend looking up the users home directory via env var.

2019-09-16 17:23 UTC, sowmiyamuthuraman commented
@beeceej I have done the changes and amended to the same commit.

2019-09-17 14:26 UTC, beeceej commented on .config/igo/config.toml
> +port = "9999"
@sowmiyamuthuraman looks like this file still stuck around can we remove it it?

2019-09-17 14:28 UTC, beeceej commented
@sowmiyamuthuraman let's just remove that config file that is in the repository. 
Once that is handled this looks good

2019-09-18 17:02 UTC, beeceej approved these changes
Looks good! Do you mind if I resolve the go.mod/go.sum conflicts myself?

2019-09-18 17:14 UTC, sowmiyamuthuraman commented
> Looks good! Do you mind if I resolve the go.mod/go.sum conflicts myself?
@beeceej I have no problem with it

2019-09-19 03:07 UTC, merged